name: slack-notification-with-optional-parameters

on: [issue_comment, pull_request_review_comment]

jobs:
  slack-notification-with-optional-parameters:
    if: (github.event.issue.pull_request != null) &&  contains(github.event.comment.body, '/slack-preview')
    runs-on: ubuntu-latest
    name: Sends a message to Slack when a push, a pull request or an issue is made
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Display Python version
        run: pip install requests
      - name: write payload
        run: |
          curl ${{ github.event.issue.url }} > payload.json
      - name: write target_url
        run: |
          python .github/write_target_url.py
         
      - name: set env
        uses: pCYSl5EDgo/cat@master
        id: TARGET_URL
        with:
          path: target_url.txt
      - name: Send message to Slack API
        uses: archive/github-actions-slack@v1.0.2
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: test-slack-previews
          slack-text: "${{ cat target_url.txt }}"
          slack-optional-icon_emoji: ":fire:"
        env:
          TARGET_URL: ${{ steps.TARGET_URL.outputs.text }}
      - name: Result from "Send Message"
        run: echo "The result was ${{ steps.notify.outputs.slack-result }}"


